version: '3.8'
services:
  bankdb:
    image: postgres
    container_name: bankdb
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb