version: '3.8'
services:
  bankdb:
    image: postgres
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    container_name: bankdb
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro